import ts from "typescript";

type DiagnosticMessage = {
  category: ts.DiagnosticCategory;
  messageText: string;
  code: number;
};

/*
  This function is from typescript internal.
*/
export function getSourceFileOfNode(node: ts.Node): ts.SourceFile;
export function getSourceFileOfNode(
  node: ts.Node | undefined,
): ts.SourceFile | undefined;
export function getSourceFileOfNode(
  node: ts.Node | undefined,
): ts.SourceFile | undefined {
  while (node && node.kind !== ts.SyntaxKind.SourceFile) {
    node = node.parent;
  }
  return node as ts.SourceFile;
}

export function createDiagnostic(
  node: ts.Node,
  message: DiagnosticMessage,
  macroStack?: string[],
): ts.DiagnosticWithLocation {
  const updatedMessage: DiagnosticMessage = macroStack
    ? {
        ...message,
        messageText: `
        ${message.messageText}
        Macro stack trace: ${macroStack}
      `,
      }
    : message;
  return {
    file: getSourceFileOfNode(node),
    start: node.pos,
    length: node.end - node.pos,
    ...updatedMessage,
  };
}

export const DiagnosticMessage = {
  DebugMessage(message: string) {
    return {
      category: ts.DiagnosticCategory.Message,
      messageText: message,
      code: 23999,
    };
  },

  MacroDefWithNoNameSymbol() {
    return {
      category: ts.DiagnosticCategory.Error,
      messageText: `
      Macro definition with no name symbol.
      This may be caused by macro generated by other preceeding transformers.
    `,
      code: 24000,
    };
  },
  MacroDefsInMacro() {
    return {
      category: ts.DiagnosticCategory.Error,
      messageText: "Cannot define macros in another macro definition.",
      code: 24001,
    };
  },
  /*
    To be precise, inside a generic function definition,
    the type parameters must not be used in a macro definition.
  */
  MacroDefsInGenericFunc() {
    return {
      category: ts.DiagnosticCategory.Error,
      messageText: "Cannot define macros in a generic function definition.",
      code: 24002,
    };
  },

  MacroCallTypeArgsMismatch() {
    return {
      category: ts.DiagnosticCategory.Error,
      messageText: "Type arguments did not match with definition.",
      code: 24100,
    };
  },
  MacroTypeParamWithNoSymbol() {
    return {
      category: ts.DiagnosticCategory.Error,
      messageText: `
      Symbol for the type parameter of the macro definition must be available at call.
      This may be caused by macro generated by other preceeding transformers.
    `,
      code: 24101,
    };
  },
  MacroTypeArgFailedToBeNode() {
    return {
      category: ts.DiagnosticCategory.Error,
      messageText: "Failed to convert resolved type arguments to AST node.",
      code: 24102,
    };
  },
  IdentifierWithNoSymbol(identifier: ts.Identifier) {
    return {
      category: ts.DiagnosticCategory.Error,
      messageText: `
      Symbol for the identifier "${identifier.escapedText}" in the macro definition must be available at call.
      This may be caused by macro generated by other preceeding transformers.
    `,
      code: 24103,
    };
  },
  InaccessibleIdentifier(identifier: ts.Identifier) {
    return {
      category: ts.DiagnosticCategory.Error,
      messageText: `
      Macro uses an inaccessible identifier "${identifier.escapedText}".
      You can import it on the call site, or inject as dependency.
    `,
      code: 24104,
    };
  },
} satisfies Record<string, (params: any) => DiagnosticMessage>; // eslint-disable-line @typescript-eslint/no-explicit-any
