import ts from "typescript";
import { enforceMembersImplement } from "./utils";

interface IDiagnosticMessage {
  category: ts.DiagnosticCategory;
  messageText: string;
  code: number;
}

/*
  This function is from typescript internal.
*/
export function getSourceFileOfNode(node: ts.Node): ts.SourceFile;
export function getSourceFileOfNode(
  node: ts.Node | undefined,
): ts.SourceFile | undefined;
export function getSourceFileOfNode(
  node: ts.Node | undefined,
): ts.SourceFile | undefined {
  while (node && node.kind !== ts.SyntaxKind.SourceFile) {
    node = node.parent;
  }
  return node as ts.SourceFile;
}

export function createDiagnostic(
  node: ts.Node,
  message: IDiagnosticMessage,
): ts.DiagnosticWithLocation {
  return {
    file: getSourceFileOfNode(node),
    start: node.pos,
    length: node.end - node.pos,
    ...message,
  };
}

export function createDiagnosticForMacroDef(
  node: ts.FunctionDeclaration,
  message: IDiagnosticMessage,
): ts.DiagnosticWithLocation {
  return createDiagnostic(node, message);
}

export function createDiagnosticForMacroCall(
  node: ts.CallExpression,
  message: IDiagnosticMessage,
): ts.DiagnosticWithLocation {
  return createDiagnostic(node, message);
}

export const DiagnosticMessage = {
  MacroDefWithNoNameSymbol: {
    category: ts.DiagnosticCategory.Error,
    messageText: `
      Macro definition with no name symbol.
      This may be caused by macro generated by other preceeding transformers.
    `,
    code: 24000,
  },
  MacroDefsInMacro: {
    category: ts.DiagnosticCategory.Error,
    messageText: "Cannot define macros in another macro definition.",
    code: 24001,
  },
  /*
    To be precise, inside a generic function definition,
    the type parameters must not be used in a macro definition.
  */
  MacroDefsInGenericFunc: {
    category: ts.DiagnosticCategory.Error,
    messageText: "Cannot define macros in a generic function definition.",
    code: 24002,
  },

  MacroCallTypeArgsMismatch: {
    category: ts.DiagnosticCategory.Error,
    messageText: "Type arguments did not match with definition.",
    code: 24100,
  },
  MacroTypeParamWithNoSymbol: {
    category: ts.DiagnosticCategory.Error,
    messageText: `
      Symbol for the type parameter of the macro definition must be available at call.
      This may be caused by macro generated by other preceeding transformers.
    `,
    code: 24101,
  },
  MacroTypeArgFailedToBeNode: {
    category: ts.DiagnosticCategory.Error,
    messageText:
      "Failed to convert resolved type arguments to AST node.",
    code: 24102,
  },
} satisfies Record<string, IDiagnosticMessage>;
